### ISSUE TITLE
目录不支持多级，只支持2级

### ISSUE THREAD

**Issue by huangxingle2009** [huang-yi/swoole-watcher#1]
目录不支持多级，只支持2级， 试了laravel ，不支持

**Comment by huang-yi** [comment]
@huangxingle2009 

非常感谢你的测试与反馈！

这个问题是由于递归方法调用错误造成的，目前已修复。[[commit]](https://github.com/huang-yi/swoole-watcher/commit/44ca253453c5f04d7300553bddb736706fbc957a)
